/* GLOSARIO — [término, frase corta, explicación, ejemplo]
   Hasta Dónde — https://github.com/  ·  licencia MIT  */

const GLOSARIO = [
 ['Deducible','La parte que siempre pagas tú.','Es el monto que la aseguradora descuenta de toda indemnización. En terremoto casi nunca se calcula sobre lo que perdiste, sino sobre el valor asegurado del bien, con un mínimo en salarios mínimos. Si la pérdida es menor al deducible, no hay pago.','Edificio de $2.000M, deducible 2% del valor asegurado = $40M. Si el daño fue de $30M, recibes cero.'],
 ['Infraseguro y regla proporcional','Si aseguraste por menos de lo que vale, te pagan proporcionalmente menos.','Cuando el valor asegurado es inferior al valor real del bien, la indemnización se reduce en la misma proporción, aunque la pérdida sea parcial y pequeña. Es la trampa silenciosa de los avalúos desactualizados.','Casa que vale $500M asegurada en $250M (50%). Pérdida de $100M → solo se reconocen $50M, y de ahí todavía sale el deducible.'],
 ['Valor asegurado vs. valor asegurable','Uno es lo que pusiste en el papel; el otro, lo que realmente vale.','El valor asegurado es la cifra que aparece en la carátula y sobre la que pagas prima. El valor asegurable es el valor real del bien. Cuando se separan, aparece infraseguro o sobreseguro.','Aseguraste la bodega en $300M en 2019 y hoy reconstruirla cuesta $520M.'],
 ['Sublímite','Un techo pequeño dentro de un techo grande.','Límite específico para un amparo determinado, menor al límite total de la póliza. Remoción de escombros, honorarios y gastos extraordinarios casi siempre tienen sublímite.','Póliza de $2.000M con sublímite de escombros del 5% = máximo $100M por ese concepto.'],
 ['Amparo','Lo que sí te cubre, escrito con nombre propio.','Cada riesgo cubierto se llama amparo y debe estar expresamente otorgado en la carátula. Lo que no aparece como amparo, no está cubierto, así parezca obvio.','Tener póliza de incendio no significa tener terremoto: son amparos distintos.'],
 ['Exclusión','Lo que la póliza dice de frente que no paga.','Lista de eventos, bienes o circunstancias que quedan por fuera aunque el amparo exista. Vive en el clausulado, no en la carátula, y por eso casi nadie la lee.','Daño preexistente, desgaste natural, defectos de construcción o falta de mantenimiento.'],
 ['Valor de reposición a nuevo','Te pagan lo que cuesta uno nuevo, sin descontar el uso.','Modalidad en la que la indemnización se calcula sobre el costo de reponer el bien nuevo. Si no está pactada, aplica valor real: te descuentan la depreciación por los años de uso.','Nevera de 8 años: a valor real te pagan quizá el 30%; a reposición a nuevo, una equivalente nueva.'],
 ['Lucro cesante','Lo que dejas de ganar mientras no puedes operar.','En pólizas empresariales cubre la utilidad y los gastos fijos durante el periodo de interrupción. Se prueba con contabilidad, no con estimaciones. Suele tener un periodo de indemnización máximo en meses.','Restaurante cerrado 4 meses: cubre la utilidad perdida y la nómina que igual tuviste que pagar.'],
 ['Remoción de escombros','Sacar los restos también cuesta, y también se reclama.','Amparo que paga demolición, retiro y disposición de escombros del bien asegurado. Tiene sublímite propio y exige facturas.','Volquetas, cuadrilla, alquiler de retroexcavadora, pago del relleno sanitario.'],
 ['Gastos extraordinarios','El sobrecosto de seguir funcionando a las malas.','Cubre lo que gastas de más para reducir la interrupción: local provisional, horas extra, transporte urgente. Debe autorizarse con la aseguradora antes de incurrir en él.','Alquilar una bodega temporal mientras reparan la tuya.'],
 ['Coaseguro','Varias aseguradoras se reparten el mismo riesgo.','Dos o más compañías asumen porcentajes de una misma póliza. Una actúa como líder y coordina el siniestro, pero cada una responde por su cuota.','Póliza de un conjunto grande repartida 60% / 40% entre dos compañías.'],
 ['Salvamento','Lo que queda sirve, y tiene precio.','Valor de los restos recuperables del bien siniestrado. Si te los quedas, la aseguradora descuenta su valor de la indemnización.','Carro declarado pérdida total: si te quedas con los restos, te descuentan lo que valen.'],
 ['Aviso de siniestro','El primer reloj que empieza a correr.','El asegurado debe avisar a la aseguradora dentro de los 3 días siguientes a la fecha en que conoció o debió conocer el siniestro (art. 1075 del Código de Comercio). La póliza puede ampliar ese plazo, y ante emergencias las compañías suelen flexibilizarlo. Avisa igual y guarda constancia.','Un correo con fecha y número de radicado vale más que diez llamadas.'],
 ['Reclamación formal','Demostrar que pasó y cuánto costó.','Al asegurado le corresponde probar la ocurrencia del siniestro y su cuantía (art. 1077 C.Co.). La aseguradora debe probar las exclusiones que alegue. Con la reclamación acreditada, tiene un mes para pagar (art. 1080); si no, corren intereses moratorios.','Carta de reclamación + fotos fechadas + cotizaciones + facturas + copia de la póliza.'],
 ['Objeción','Cuando la aseguradora dice que no.','La negativa debe ser seria, motivada y por escrito. No es la última palabra: la mayoría se resuelve aportando la prueba que faltaba, y para eso está tu asesor. Si el caso no se destraba, existe el Defensor del Consumidor Financiero de la entidad, gratuito.','“Objetamos por exclusión de preexistencia” sin explicar cuál preexistencia no es una objeción seria.'],
 ['Prescripción','La fecha límite para reclamar.','La acción derivada del contrato de seguro prescribe en 2 años contados desde que el interesado conoció o debió conocer el hecho (prescripción ordinaria, art. 1081 C.Co.). Hay también una prescripción extraordinaria de 5 años. No dejes que se venza.','Sismo del 10 de agosto de 2026 → el reloj ordinario corre hasta agosto de 2028.'],
 ['Coeficiente de copropiedad','Tu porcentaje del edificio.','Índice que fija la participación de cada unidad en los bienes comunes. Determina cuánto aportas y, si la indemnización llega a repartirse, cuánto te toca.','Apartamento con coeficiente de 1,8% recibe el 1,8% de lo que se reparta.'],
 ['Ajustador','El perito que le pone número al daño.','Profesional independiente contratado por la aseguradora para verificar la ocurrencia y valorar la pérdida. Su informe pesa mucho, así que conviene estar presente en la visita y tener a la mano las cotizaciones.','Si su cifra queda por debajo de la tuya, se sustenta con cotizaciones formales: ahí es donde el asesor negocia el número.'],
 ['Cláusula de valor admitido','El valor pactado no se discute.','Cuando se pacta, la aseguradora acepta de antemano el valor del bien y renuncia a aplicar la regla proporcional. Es el mejor antídoto contra el infraseguro.','Maquinaria especializada asegurada con valor admitido: no te aplican infraseguro aunque el avalúo cambie.'],
 ['Primer riesgo absoluto','Cubierto hasta el tope, sin castigo por infraseguro.','Modalidad en la que se asegura una suma menor al valor total, pero se indemniza el 100% de la pérdida hasta ese límite sin aplicar regla proporcional. Útil cuando es improbable perderlo todo.','Contenidos asegurados a primer riesgo por $80M: si pierdes $50M, te reconocen $50M completos.']
];

export { GLOSARIO };
